### PR TITLE
Travis: migration to a new config

### PR DESCRIPTION
**Pull request by Anton-Latukha**

### CODE REVIEW

**Comment by chshersh** [comment]
@Anton-Latukha This repository is not used by our company anymore. So I guess there's no need to maintain it? @Martoon-00 could you clarify this?

**Comment by Martoon-00** [comment]
Now it's only used to get some :star:s to overall of serokell github accout, perhaps nothing more :pensive:

**Comment by Anton-Latukha** [comment]
Yea.

I know that it is not very active, and that new generation moved inside Cardano.

But there was lately update to newer LTS. And I understood that if it is here, and maintained - this is probably in use for something.

**Comment by Anton-Latukha** [comment]
We have a number of Serokell repositories that are far more deserve to be deleted.

**Comment by Anton-Latukha** [comment]
But I got a bit more experimentation and practice while doing `time-warp` =))

**Pull request closed without merging**
